"""empty message

Revision ID: 12ae85d17d9b
Revises: 1ceef5cf479c
Create Date: 2024-12-19 12:52:42.109471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ae85d17d9b'
down_revision = '1ceef5cf479c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###
