"""empty message

Revision ID: 13574a96e3a1
Revises: 12ae85d17d9b
Create Date: 2024-12-19 19:04:50.849728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13574a96e3a1'
down_revision = '12ae85d17d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    op.drop_table('favorite')
    # ### end Alembic commands ###
